// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateApartment(arg1:string,arg2:number,arg3:string):Promise<models.Apartment>;

export function CreateHouse(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<models.House>;

export function DeleteApartment(arg1:number):Promise<void>;

export function DeleteHouse(arg1:number):Promise<void>;

export function GetAllApartments():Promise<Array<models.Apartment>>;

export function GetAllHouses():Promise<Array<models.House>>;

export function GetApartmentByID(arg1:number):Promise<models.Apartment>;

export function GetApartmentsByHouseID(arg1:number):Promise<Array<models.Apartment>>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetHouseByID(arg1:number):Promise<models.House>;

export function UpdateApartment(arg1:number,arg2:string,arg3:number,arg4:string):Promise<models.Apartment>;

export function UpdateHouse(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<models.House>;
