// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateHouse(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateHouse'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteHouse(arg1) {
  return window['go']['main']['App']['DeleteHouse'](arg1);
}

export function GetAllHouses() {
  return window['go']['main']['App']['GetAllHouses']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetHouseByID(arg1) {
  return window['go']['main']['App']['GetHouseByID'](arg1);
}

export function UpdateHouse(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateHouse'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
